Implement "Strict" validation logic in the "shrike.build.prepare"
Azure/shrike pull request #111
Opened 2021-06-30 02:29 UTC by haozhestat

This PR is the implementation of the [proposal](https://azure.github.io/shrike/rfc/strict-component-validation.html) for strict validation of Azure ML components

2021-06-30 02:46 UTC, haozhestat commented
@dkmiller : This is a draft PR for component validation. It would be great if you could take a look. I will start writing unit tests for all added functions and changed functions, if this PR looks good to you.

2021-07-01 23:04 UTC, dkmiller requested changes

2021-07-01 23:04 UTC, dkmiller commented on shrike/build/commands/prepare.py
> +ALLOWED_CONTAINER_REGISTRY = ["polymerprod.azurecr.io"]
Since these are arrays, should names be plural? E.g., `*_REGISTRIES`, `*_FEEDS`?

2021-07-01 23:04 UTC, dkmiller commented on shrike/build/commands/prepare.py
> +        if pip_dependencies:
Can you factor this logic into a standalone method?

Also, why is this needed?

2021-07-01 23:04 UTC, dkmiller commented on shrike/build/commands/prepare.py
> +                if re.match("^--index-url", dependency):
Should also catch `--extra-index-url`.

2021-07-01 23:44 UTC, haozhestat commented on shrike/build/commands/prepare.py
> +        if pip_dependencies:
@dkmiller : I don't quite understand your question. Could you elaborate more?

To do component validation, I need to parse the conda dependencies and conda channels from the spec and env yaml files. Rather than writing a new function for parsing, I decided to refactor and reuse the code originally written by Fuhui to extract the dependencies and channels. Explicitly, I took some code out of the function `_create_requirements_file_for_single_component()` and wrapped into a new function `_extract_dependencies_and_channels()`.

This new function `_extract_dependencies_and_channels()` is used in `_create_requirements_file_for_single_component()` and `compliance_validation()`

2021-07-01 23:49 UTC, haozhestat commented on shrike/build/commands/prepare.py
> +ALLOWED_CONTAINER_REGISTRY = ["polymerprod.azurecr.io"]
Addressed.

2021-07-01 23:49 UTC, haozhestat commented on shrike/build/commands/prepare.py
> +                if re.match("^--index-url", dependency):
Addressed.

2021-07-02 15:13 UTC, dkmiller commented on shrike/build/commands/prepare.py
> +        if pip_dependencies:
@haozhestat thanks for clarifying, I think I missed that you weren't adding net-new logic here, just moving around.

2021-07-02 15:14 UTC, dkmiller approved these changes
Looks good!

One last suggestion: try it out against, e.g., the accelerator repo to make sure nothing breaks.

2021-07-02 15:48 UTC, haozhestat commented
> One last suggestion: try it out against, e.g., the accelerator repo to make sure nothing breaks.

@dkmiller : I just found that our accelerator repo and the `signed-components` folder contain both eyes-off and eyes-on components. If I enable component validation in the accelerator repo, the validation will fail for sure due to the non-compliant docker image URL.

https://dev.azure.com/msdata/Vienna/_git/aml-ds?path=%2Frecipes%2Fcompliant-experimentation%2Fcomponents%2Fprs_component%2Fcomponent_spec_linux_eyeson.yaml&version=GBmain&line=29&lineEnd=30&lineStartColumn=4&lineEndColumn=9&lineStyle=plain&_a=contents

2021-07-02 15:59 UTC, merged