Implement Spark .NET runner logic
Azure/shrike pull request #119
Opened 2021-07-07 23:34 UTC by dkmiller

Implement logic for easily running Spark .NET from PySpark applications.

Closes #30 .

## Changes

- Add logic for shelling out to Spark .NET, catching exceptions, and printing usable logic.

## Future

- Logic for showing the C\# stack trace ( #62 ).

## Key files

- `spark_net.py`

## To-do

- [x] Validate in MyData workspace. [ [Run 39](https://ml.azure.com/runs/47c68470-66a2-4ead-b182-48d5ae53f4a8?wsid=/subscriptions/27a3c1ec-7827-4d89-93b8-dfbb82e9c56f/resourcegroups/HERON.PROD.c3901b6a-8f0c-49f3-a994-e47330da8849/workspaces/amlworkspacexdjqlwufhgfss&tid=72f988bf-86f1-41af-91ab-2d7cd011db47) ]
- [ ] Add unit tests.
- [ ] Add additional docstrings.

2021-07-08 20:45 UTC, haozhestat requested changes
@dkmiller: Apart from unit tests for these spark functions, we may also need to add a new doc page on spark .net to https://azure.github.io/shrike/. This documentation work could be done in a separate PR.

2021-07-08 20:45 UTC, haozhestat commented on shrike/spark/spark_net.py
> +"""
Could you add copyright statement here? Otherwise, the ci-gate build will fail.

2021-07-08 20:45 UTC, haozhestat commented on shrike/spark/spark_net.py
> +    import py4j
Should we add the dependencies `py4j` and `pyspark` into any requirement files? I am wondering whether we need to have another extra dependency such as `pip install shrike[spark,pipeline,build,dev]`?

2021-07-08 20:45 UTC, haozhestat commented on shrike/spark/spark_net.py
> +    SparkContext = Any
I suggest that we add a warning or error message here if the importing fails.

2021-07-08 20:56 UTC, dkmiller commented on shrike/spark/spark_net.py
> +    import py4j
Those exist by default in Spark clusters capable of running pySpark.

2021-07-08 23:09 UTC, haozhestat approved these changes

2021-07-08 23:09 UTC, haozhestat commented on docs/spark/advanced-use.py
> +import argparse
I think copyright statement is also required for python files in the docs.

2021-07-08 23:09 UTC, haozhestat commented on docs/spark/examples.md
> +# Examples
Could you update the readme file with one-sentence introduction on spark .net?

![image](https://user-images.githubusercontent.com/18077361/125001084-b66db200-e006-11eb-995f-b397e6197d41.png)

2021-07-09 22:17 UTC, haozhestat commented
@dkmiller: I just notice that the spark unit test has not been added into the CI-gate build yet. Could you add it?

https://github.com/Azure/shrike/blob/main/.github/workflows/python.yml

2021-07-19 17:55 UTC, merged