Add documentation on the "strict" component validation
Azure/shrike pull request #139
Opened 2021-07-22 21:19 UTC by haozhestat

Add a paragraph about "strict" component validation in the documentation page about signing \& registering.

2021-07-22 21:24 UTC, thomasp-ms commented on docs/build/build-for-sign-and-register.md
> +name to start with "office.smartcompose." could be translated to
you probably mean "smartreply" here

2021-07-22 21:26 UTC, thomasp-ms requested changes
Looks good, except for that typo on which I commented. You'll probably want for someone else to take a look too though, I went quickly on this

2021-07-22 21:28 UTC, haozhestat commented on docs/build/build-for-sign-and-register.md
> +name to start with "office.smartcompose." could be translated to
Thanks for catching it. I just updated it.

2021-07-23 00:10 UTC, thomasp-ms approved these changes

2021-07-23 00:34 UTC, merged