Fix to some smaller bugs in the compliant Logger module
Azure/shrike pull request #147
Opened 2021-07-29 13:55 UTC by felixnext

Some small bug fixes:

## Changes

- Fixed bug where None values in dict could break the metric function /
- Fixed format commands on f-strings /
- Added additional exception handling to the library import (in case library is broken)

## Future

- You may show was is explicitly _not_ in the scope of this pull request.

## Key files

- logger.py
- system_info.py

## To-do

- [ ] If you have any action items which can't easily be expressed as comments
  on the pull request, or need to be carried out after the pull request is
  completed, express them as Markdown checkboxes.

2021-07-29 14:37 UTC, dkmiller requested changes
You'll need to do a patch version bump as well.

2021-07-29 14:37 UTC, dkmiller commented on shrike/compliant_logging/logging.py
> +                            col = col[i] if i < len(col) and col[i] is not None else ""
You can just put `col[i] if i < len(col) and col[i] else ""`, Python's boolean coercion treats `col[i]` and `col[i] is not None` the same.

2021-07-29 15:38 UTC, haozhestat reviewed
Could you update the unit tests as well

2021-08-03 14:55 UTC, dkmiller approved these changes
Thanks for contributing!

2021-08-03 15:35 UTC, felixnext commented
@dkmiller @haozhestat  I do not think that I have access to the PyPi deployment project. Would one of you do that and complete the merge?

2021-08-03 15:44 UTC, merged