Replace print statements with Python logging in pipelines module
Azure/shrike pull request #165
Opened 2021-08-09 18:28 UTC by dkmiller

First stab towards #104 .

## Changes

- Replace `print` with `log.*` statements throughout in the pipelines module.
- Add `AMLPipelineHelper` to the top-level `shrike.pipeline` namespace for easier import.

## Future

- Add the logging library's `DataCategory` parameters throughout.

## To-do

- [ ] Align to Python logging conventions (no `--` at start of log lines, leverage log levels).

2021-08-09 19:00 UTC, fuhuifang requested changes
Some unit tests are checking the stdout, and they need to be adjusted accordingly, e.g.: https://github.com/Azure/shrike/blob/a588e07f99656c9681d5aaaff9eb6888b0143692/tests/tests_pipeline/test_pipeline_helper.py#L301

2021-08-09 19:08 UTC, haozhestat requested changes

2021-08-12 15:59 UTC, haozhestat approved these changes

2021-08-12 16:16 UTC, fuhuifang approved these changes

2021-08-12 16:16 UTC, merged