added custom params to subgraph load
Azure/shrike pull request #172
Opened 2021-08-17 06:28 UTC by AliMahmoudzadeh

Current implementation forces subgraphs to use the same config as the pipeline. This prevents users to call variations of the same subgraph with build-time conditionals. This PR, enables some built time parameterization in the subgraphs.

## Usage:
- in your code, load the subgraph inside the build with the custom parameters
- instantiate the use the subgraph
`feature_extraction_one_func = self.subgraph_load(
                        "BingImageFeatureExtractionOnePipeline", custom_params={
                        "pipeline_name": "feature_extraction_one",
                        "enable_ndcg": True)`

## Changes

- method "subgraph_load" is updated to take an optional argument custom_params
- These custom params will be added to the pipeline config before the config being passed to the subgraph

## Key files
- shrike/pipeline/pipeline_helper.py

## To-do

2021-08-17 15:24 UTC, dkmiller requested changes
Made a comment on making the design more flexible.

Also, you'll want to

- add unit tests
- examples (in the docs) for this new functionality.
- version-bump to `1.11.0`

2021-08-17 15:24 UTC, dkmiller commented on shrike/pipeline/pipeline_helper.py
> +    def subgraph_load(self, subgraph_key, custom_params={}) -> Callable:
Suggestion: rather than just supporting a dictionary input, consider supporting nested objects as well, and using `omegaconf`'s merging logic.

That way, users can pass nested configuration to subgraphs, not just a simple collection of key-value pairs.

2021-08-20 05:52 UTC, AliMahmoudzadeh commented on shrike/pipeline/pipeline_helper.py
> +    def subgraph_load(self, subgraph_key, custom_params={}) -> Callable:
@dkmiller Following your suggestions,
1- dict was replaced with omegaconf for a multi-level custom config
    - I didn't use built-in merge, as I couldn't make it work with structs
2- unit tests for sungraph loads with and without custom parameters are added
3- explanations are added to the doc. We can also link to the unit test for an example
4- version is bumped to 1.11.0

2021-08-20 16:00 UTC, haozhestat approved these changes

2021-09-07 23:01 UTC, dkmiller approved these changes

2021-09-14 20:42 UTC, merged