Federated learning RFC
Azure/shrike pull request #176
Opened 2021-08-23 04:49 UTC by fuhuifang

2021-08-23 18:23 UTC, dkmiller requested changes
Left a bunch of initial comments.

Meta-point: love to see the design work starting here!

2021-08-23 18:23 UTC, dkmiller commented on docs/rfc/federated-learning.md
> +1. How are the model weights aggregated after each "training" round?
User should configure a component / pipeline to do the weight aggregation. It should accept "N inputs"

Platform ask: `args` (N input datasets) as input to a single component. Worst-case scenario, we can do some kind of "merge folders" hack in advance.

2021-08-23 18:23 UTC, dkmiller commented on docs/rfc/federated-learning.md
> +An alternative solution is to define the required method `federated_config`, which returns (in order): preprocess pipeline, midprocess pipeline, postprocess pipeline, training pipeline. Shrike will i
Personally, I think the alternative design makes a bit more sense. As long as we provide a good extensibility / override model, we want a "happy path" with minimal boilerplate.

Consider looking at PyTorch Lightning vs. "raw" PyTorch for inspiration.

2021-08-23 18:23 UTC, dkmiller commented on docs/rfc/federated-learning.md
> +        def midprocess(self, config):
How will data move between the preprocess, midprocess, etc. steps?

2021-08-23 19:03 UTC, haozhestat reviewed
Future work: We may need to consider the drop-out or failure of some

2021-08-23 23:12 UTC, thomasp-ms commented on docs/rfc/federated-learning.md
> +    │            │           └─── eyesoff.yaml  # see example below
Minor, but why not add a simple sentence like "info on compute targets, data stores, silos..."? The space is lost anyway, and it would make the diagram a little more self-contained.

Same comment for the below line on submit.yaml

2021-08-23 23:14 UTC, thomasp-ms commented on docs/rfc/federated-learning.md
> +    │            └──────── modules  # contains some yaml files describing which components in `components` or remote copies will be used
if this has a single file as usual, why not list it like was done above for aml and compute?

2021-08-23 23:16 UTC, thomasp-ms commented on docs/rfc/federated-learning.md
> +    │            │           └─── eyesoff.yaml  # see example below
actually, same comment again for submit.py and pipeline_definition.py. I think it would be nice if the first diagram contained some basic info, even if incomplete

2021-08-23 23:33 UTC, thomasp-ms commented on docs/rfc/federated-learning.md
> +            postprocess_pipeline_step = postprocess_pipeline(input = training_pipeline_step.outputs.output1,
I might very well be missing something obvious here, but I find it strange that the postprocess step does not seem to be using the latest set of weights from the midprocess step. Shouldn't it be "input = aggregation_step.outputs.output1" instead?

2021-08-23 23:43 UTC, thomasp-ms commented on docs/rfc/federated-learning.md
> +    compute: gpu-cluster-1
shouldn't this part contain the workspace info for the silos too? 

(apologies in advance if for now we're just considering the case where the silos are in the same workspace)

2021-08-23 23:46 UTC, thomasp-ms commented on docs/rfc/federated-learning.md
> +            # self.apply_smart_runsettings(preprocess_pipeline_step)    # required if preprocess is a component, instead of a subgraph
Do we really want to support the component case too? I'm not sure how often people will have their whole step encapsulated in a single component, plus it opens up some room for errors (mostly forgetting to call the apply_smart_runsettings).

If it was already discussed and decided that's fine, but if it wasn't really discussed, maybe it's worth talking about...

2021-08-24 01:10 UTC, fuhuifang commented on docs/rfc/federated-learning.md
> +            postprocess_pipeline_step = postprocess_pipeline(input = training_pipeline_step.outputs.output1,
My understanding is postprocess is very similar to midprocess. It should be midprocess + some additional processing for final output. In this case, the workflow should be: ... training -> midprocess -> training -> postprocess.

2021-08-24 22:40 UTC, simra commented on docs/rfc/federated-learning.md
> +        def training(self, config, input):
I wonder how often we will see the need to have a custom training method per-silo.  It might be useful to promote these four methods to class members so they can be overridden/inherited.  Then it could be possible to associate each silo with a specific class derived from FederatedPipelineBase.

The design also assumes the orchestrator has significant power over the silos- whoever runs code in the orchestrator can effectively inject any code they want to run in each silo.  Maybe the design should allow room for the individual silos to control their own internal train() pipeline and this method is more of an RPC into the silo to execute code owned by the silo.  (Maybe this feature is better left for V2 :-))

2021-08-24 22:47 UTC, simra commented on docs/rfc/federated-learning.md
> +                training_pipeline_step = training_pipeline(input = config.federation.training.input1,
It's harder for me to imagine here how we might allow for per-silo variability. Maybe some silos fetch data from sql and others from blob storage- we have to encode every kind of business logic into a single pipeline class, or have some mapping under the hood to invoke a silo-specific helper class that does the actual training.

2021-09-03 18:25 UTC, dkmiller commented
@fuhuifang one other thing that came out of conversations with Shize.

We'll want the library to have a kind of "debug" mode where it turns off all data transfer and assumes no approval endpoint. This way, data scientists could quickly debug with "dummy" (artificial) silos in eyes-on or reserach contex.t

2021-09-14 20:17 UTC, fuhuifang commented
I think this RFC is ready to merge as a first version, as AML DS + FTL have reached a consensus. For the next round, we can write another one with implementation details.

2021-09-14 22:01 UTC, dkmiller approved these changes

2021-09-14 22:23 UTC, merged