Implement is_eyesoff() method
Azure/shrike pull request #242
Opened 2021-11-18 01:04 UTC by fuhuifang

- [ ] "pipeline" part implementation + unit test
- [ ] "logging" part implementation + unit test

2021-11-18 15:50 UTC, dkmiller requested changes

2021-11-18 15:50 UTC, dkmiller commented on shrike/pipeline/eyeson_subscription.txt
> +dfcaf96e30a340fae2fcd5871a5e94cf3805f6521d5e2571d55b097df857c9c3
Suggestion: put this list into the default pipeline configuration. I'm not sure how well the library will pick up `.txt` files into the generated wheel file.

This way, users also have the option of overriding this list.

If you can't put it into default configuration, just check it in as a Python set:

```python
EYES_ON_SUBSCRIPTIONS = set(
    "dfcaf96e30a340fae2fcd5871a5e94cf3805f6521d5e2571d55b097df857c9c3"
)
```

2021-11-18 15:50 UTC, dkmiller commented on shrike/pipeline/pipeline_helper.py
> +        if workspace.get_details()["identity"]["tenant_id"] != torus_tenant_id:
Suggest: `...["tenant_id"].lower() != ...`, since tenant IDs are case-sensitive.

2021-11-18 15:50 UTC, dkmiller commented on shrike/pipeline/pipeline_helper.py
> +        torus_tenant_id = "cdc5aeea-15c5-4db6-b079-fcadd2505dc2"
Suggestion: make this a constant in the file: `EYES_OFF_TENANT_ID = ...` near top of file.

2021-11-18 15:50 UTC, dkmiller commented on tests/tests_pipeline/test_pipeline_helper.py
> +# The following test only works with personal identity
Suggestion: create a "mock" workspace object that doesn't require authentication for more detailed unit tests.

2021-11-18 15:50 UTC, dkmiller commented on shrike/__init__.py
> +__version__ = "1.12.3"
This should be &mapsto; 1.**13**.0 since you're adding new functionality.

2021-11-18 15:50 UTC, dkmiller commented
@dansc , you may be interested in reviewing this as well.

2021-11-18 20:08 UTC, haozhestat commented on shrike/pipeline/pipeline_helper.py
> +                return True
Does it mean that `is_eyesoff()` will return `True` if an eyes-on workspace is not in the allowed eyes-on list?

2021-11-18 20:08 UTC, haozhestat commented on shrike/pipeline/pipeline_helper.py
> +                return True
Why do we need an `allowlist` here?

2021-11-18 21:04 UTC, dkmiller commented on shrike/pipeline/pipeline_helper.py
> +                return True
@haozhestat , the guiding principal is:

> False negatives (incorrectly classify eyes-off as eyes-on) are **very bad**, false positives (incorrectly classify eyes-on as eyes-off) are only inconvinient.

Since there will be both kinds of workspaces in Torus soon, the only thing we can do is have a list of "currently known" eyes-on subscriptions in Torus, and update that periodically. This will guarantee no false negatives.

2021-11-19 01:41 UTC, fuhuifang commented on tests/tests_pipeline/test_pipeline_helper.py
> +# The following test only works with personal identity
@dkmiller Can you review the unit test?
https://github.com/Azure/shrike/blob/a7f986a70ab379b0be8504520657f48159ce4be7/tests/tests_pipeline/test_pipeline_helper.py#L729

2021-11-19 16:27 UTC, dkmiller commented on tests/tests_pipeline/test_pipeline_helper.py
> +def test_is_eyesoff_Torus():
Once you add the full list of "known eyes-on Torus subscriptions", can you add a test checking that the AIMS eyes-on Torus sub shows as eyes-on? 2ffad2ef-10c3-4793-aacc-093dc4ad2e63

2021-11-19 19:45 UTC, fuhuifang commented on tests/tests_pipeline/test_pipeline_helper.py
> +def test_is_eyesoff_Torus():
Where can I find the list of known eyes-on Torus subscriptions? Matt's list seems to be eyes-off.

2021-11-19 20:50 UTC, dkmiller commented on tests/tests_pipeline/test_pipeline_helper.py
> +def test_is_eyesoff_Torus():
Ideally, it would be all Torus subscriptions containing AML workspaces that are _not_ in the list of eyes-off subs.

Here's a start &mdash; [query](https://ms.portal.azure.com#@72f988bf-86f1-41af-91ab-2d7cd011db47/blade/Microsoft_Azure_Monitoring_Logs/LogsBlade/resourceId/%2Fsubscriptions%2Ff12aca23-53d1-4587-9e3e-740318475a18%2FresourceGroups%2Fux-workspaceportal%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fworkspaceportal-prod/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAA43NMQ7CMAxA0Z1TRJ2aIahUBMSQjYUZxJ7aphi1SRW76sLh6YiYOMB%252Ff4o93ZkW2bzN8qRCRvOQFyq1ZtHCqa9hFs3jmUdKwjnJ9kYpJrXWhGAqQPCRKLqdB%252B%252F22B1c1xxP7gERsfWNR2irFZ9KfhGouc6dQOFJV8qEP27fwQWtXS1kUU4%252F2AddIUzgygAAAA%253D%253D/timespan/P1D) &mdash; though this list isn't _all_ subscriptions, just subscriptions with AML page views.

May be worth asking around AML engineering to see if there's a good list of (workspace, subscription, tenant ID) tuples in logs anywhere.

2021-11-19 22:40 UTC, fuhuifang commented on tests/tests_pipeline/test_pipeline_helper.py
> +def test_is_eyesoff_Torus():
This is very helpful: https://azure.microsoft.com/en-us/blog/azure-resource-explorer-a-new-tool-to-discover-the-azure-api/

2021-11-20 00:45 UTC, fuhuifang commented on shrike/pipeline/utils.py
> +    with open("torus_subscription.json", "r") as f:
@dkmiller  I think the two files mentioned here should not be uploaded along with the library. They should be re-created by shrike owners locally for regular or ad-hoc updates. Do you have any thoughts?

2021-11-22 18:53 UTC, dkmiller commented on shrike/pipeline/utils.py
> +    with open("torus_subscription.json", "r") as f:
@fuhuifang , that's the approach the internal library [aml-graph-node](https://dev.azure.com/eemo/TEE/_wiki/wikis/aml-graph-node%20wiki/904/Setting-up-a-project?anchor=create-the-workspace-configuration-directory-and-files) takes. The tricky thing is that:

- The same list / logic needs to be used both in jobs (logging library) and in pipelines (e.g., to insert data transfer steps). There's no straightforward way to share the same file between a bunch of components _and_ a bunch of pipelines.
- The logic around what should go in the file is basically the same for everyone, which means we'll be forcing users of Shrike to duplicate the effort.
- The first thing users will do is ask us which subscriptions are eyes-on vs. eyes-off.

In light of those considerations, I think it makes sense for Shrike to own a central list that guarantees no "false negatives" (incorrectly classify eyes-off as eyes-on) that folks can just pick up and use.

If customers want to write their own list and use it, there's nothing stopping them :)

2021-11-22 19:07 UTC, fuhuifang commented on shrike/pipeline/utils.py
> +    with open("torus_subscription.json", "r") as f:
Agreed. The set here https://github.com/Azure/shrike/blob/717704fd662ddb34b2db11cba33a6fa3f5385244/shrike/pipeline/pipeline_helper.py#L52 is the guaranteed eyes-on subscription hashes, generated from this utils.py. The question is for the raw files of subscription ids, do we still want to keep them in the library as well? I think the set is good enough.

2021-11-22 19:09 UTC, dkmiller commented on shrike/pipeline/utils.py
> +    with open("torus_subscription.json", "r") as f:
Ahh, I misunderstood, thanks for clarifying!

No, I don't think we need to keep the raw files in the library; this set is enough.

2021-11-24 15:51 UTC, dkmiller requested changes
The logic and tests look good!

Some minor suggestions around restructuring files.

2021-11-24 15:51 UTC, dkmiller commented on shrike/_core/utils.py
> +# Copyright (c) Microsoft Corporation.
Meta-suggestion: rename this file to something like `eyesoff.py`. Generally, we should try to avoid files, classes, or methods named "utils" or "helper".

2021-11-24 15:51 UTC, dkmiller commented on shrike/compliant_logging/logging.py
> +        tenant_id = os.environ["AZ_BATCHAI_CLUSTER_TENANT_ID"]
This implementation will fail if running locally, where the values `AZ_BATCHAI_CLUSTER_TENANT_ID` do not exist.

Suggestion: use `os.environ.get("AZ_BATCHAI_CLUSTER_TENANT_ID", "")` to get an empty string for `tenant_id` if the environment variable isn't defined.

2021-11-24 15:51 UTC, dkmiller commented on shrike/pipeline/pipeline_helper.py
> +    def is_eyesoff(self):
Suggestion: add `-> bool` type hint.

2021-11-24 15:51 UTC, dkmiller commented on shrike/compliant_logging/logging.py
> +    def is_eyesoff(self) -> bool:
One last suggestion: this method doesn't need to be attached to the logger. I'd move it to `shrike.compliant_logging.logging.is_eyesoff`.

Other suggestion: put this method in `compliant_logging/__init__.py`, so someone can do `from shrike.compliant_logging import is_eyesoff`.

2021-11-24 18:25 UTC, dkmiller approved these changes

2021-11-24 18:43 UTC, merged