relax schema check to determine use_component_sdk
Azure/shrike pull request #247
Opened 2021-11-24 01:51 UTC by wangchao1230

Relax the schema checks. 

Possible schema could be something like: 
$schema: https://componentsdk.azureedge.net/jsonschema/CommandComponent.json

2021-11-24 01:55 UTC, Anbang-Hu approved these changes

2021-11-24 21:38 UTC, dkmiller requested changes
You'll need to version bump the library in `shrike/__init__.py`.

2021-11-24 21:38 UTC, dkmiller commented on shrike/pipeline/testing/components.py
> +        if "$schema: http" in component_spec_content:
Let's make sure schema is like `http(s)://`. I.e., either `http://` or `https://`. Ideally, just `https://`.

2021-11-25 02:51 UTC, wangchao1230 commented on shrike/pipeline/testing/components.py
> +        if "$schema: http" in component_spec_content:
Updated. 
Yeah ideally should be https://.
But as users are using http://, so we would have to keep backward compatibility.

2021-11-29 03:28 UTC, haozhestat approved these changes

2021-11-29 15:51 UTC, merged