Shrike's preparation logic generates environment.yml file for Conda-native dependencies
Azure/shrike pull request #256
Opened 2021-12-03 08:42 UTC by haozhestat

To put Conda deps in environment.yml and put pip deps in requirements.txt.

2021-12-06 19:30 UTC, dkmiller requested changes
One minor comment, also a bit concerned by the drop in code coverage. Can you add some additional tests? If it's hard to think of tests to add, probably an indication you should split up the code...

2021-12-06 19:30 UTC, dkmiller commented on shrike/build/commands/prepare.py
> +                        file.write(req)
Suggestion: use the `writelines` method.

2021-12-08 19:42 UTC, fuhuifang approved these changes

2021-12-08 19:42 UTC, fuhuifang commented on tests/tests_build/commands/test_prepare.py
> +    assert os.path.exists(component_dependencies_repo + "/dummy/environment.yml")
Not sure if this helps with coverage rate, but you could try adding "assert not exist" for environment.yml before calling `_create_dependencies_files()`.

2022-01-20 23:17 UTC, dkmiller approved these changes

2022-01-21 00:31 UTC, haozhestat commented
> One minor comment, also a bit concerned by the drop in code coverage. Can you add some additional tests? If it's hard to think of tests to add, probably an indication you should split up the code...

@dkmiller: I just checked the coverage report ([Codecov](https://app.codecov.io/gh/Azure/shrike/compare/256/overview)). After merging this PR into main, the coverage rate will increase 0.08%.

2022-01-21 00:31 UTC, merged