When component key is not in manifest, try to load the component from the workspace
Azure/shrike pull request #262
Opened 2021-12-18 03:09 UTC by thomasp-ms

Adding functionality to log a warning and load a component from the workspace when it is not present in the module manifest. This behavior is enabled when the new key in the `module_loader` config (`use_remote_when_module_not_in_manifest`) is set to `True`. When it is set to `False` or left unspecified (default behavior), we recover the usual behavior (throw an exception and don't attempt to load from the workspace).

Closes #192

2021-12-20 16:06 UTC, dkmiller requested changes

2021-12-20 16:06 UTC, dkmiller commented on shrike/pipeline/module_helper.py
> +    use_remote_when_module_not_in_manifest: Optional[bool] = False
Nit: this should be `use_remote_when_component_not_in_manifest` to reflect "modern" naming.

2021-12-20 16:06 UTC, dkmiller commented on shrike/pipeline/module_helper.py
> +        self.use_remote_when_module_not_in_manifest = (
Nit: since this has a default value, you shouldn't have to have this `if "..." in ...` statement. You _should_ just be able to put `self.use_... = config.module_loader.*`.

2021-12-20 16:06 UTC, dkmiller commented on shrike/pipeline/module_helper.py
> +            f"AMLModuleLoader initialized (use_local={self.use_local}, force_default_module_version={self.force_default_module_version}, force_all_module_version={self.force_all_module_version}, loca
Nit: this string is getting very long. Suggest breaking it up into either separate log statements, or a multiline string that we log.

2021-12-20 16:06 UTC, dkmiller commented on shrike/pipeline/module_helper.py
> +                raise Exception(
Nit: suggest `LookupError` or `KeyError` instead of the "generic" base exception.

2021-12-20 16:06 UTC, dkmiller commented on shrike/pipeline/module_helper.py
>      def load_config_manifest(self, config):
Nit: suggest adding a type hint `-> Tuple[?, ?, bool]` since this method is starting to get complicated.

2021-12-21 01:16 UTC, thomasp-ms commented on shrike/pipeline/module_helper.py
> +        self.use_remote_when_module_not_in_manifest = (
That's what I thought too and initially tried, but if I do that the AML ModuleCreation fails if this key isn't provided in the config. Same issue if I try the same thing with the `use_local_except_for` key. Let's chat in person about this one

2021-12-21 21:47 UTC, dkmiller approved these changes
Looks good! Please file two follow-up issues:

1. Vaex versioning
2. Need for `config.* if "*" in config` in module helper

2021-12-21 21:55 UTC, merged