Add a built-in aggregation component to FL APIs
Azure/shrike pull request #286
Opened 2022-01-25 04:52 UTC by fuhuifang

2022-01-26 22:50 UTC, dkmiller requested changes
PS, suggest you test this by manually building the wheel, pip-installing it from _outside_ the repo, then making sure things still work.

2022-01-26 22:50 UTC, dkmiller commented on MANIFEST.in
> +recursive-include shrike/pipeline/components *
Nit: include a "blank" newline at the end of this file to make future Git diffs cleaner.

2022-01-26 22:50 UTC, dkmiller commented on shrike/__init__.py
> +__version__ = "1.15.1"
Nit: make this `1.16.0` since we're adding new functionality (embedded components).

2022-01-26 22:50 UTC, dkmiller commented on shrike/pipeline/components/fedavg/env.yaml
> +name: fl
Suggest naming this and other component environments something more specific to the component, e.g. `fl-fedavg`.

2022-01-26 22:50 UTC, dkmiller commented on shrike/pipeline/components/fedavg/spec.yaml
> +    type: AnyDirectory
Suggestion: make these `path` and update the component to handle either files or directories.

2022-01-26 22:50 UTC, dkmiller commented on shrike/pipeline/components/fedavg/spec.yaml
> +  helpDocument: https://aka.ms/aml-ds/fl
Nit: this should be shrike-docs or some page there, not an internal link.

2022-01-26 22:50 UTC, dkmiller commented on shrike/pipeline/components/fedavg/spec.yaml
> +  Office: null
Nit: remove this "Office" tag.

2022-01-26 22:50 UTC, dkmiller commented on shrike/pipeline/components/fedavg/spec.yaml
> +  contact: aml-ds@microsoft.com
Suggestion: replace this with aims-team.

2022-01-26 22:50 UTC, dkmiller commented on shrike/pipeline/components/fedavg/spec.yaml
> +  additional_arguments: python run.py --model_output_dir {outputs.model_output_dir}
Suggestion: one parameter per line, i.e.

```yaml
launcher:
  additional_arguments: >-
    python run.py
    --model_output_dir {outputs.model_output_dir} 
    --num_models {inputs.num_models}
    [--weights {inputs.weights}]
    ...
```

2022-01-26 22:50 UTC, dkmiller commented on shrike/pipeline/components/fedavg/spec.yaml
> +name: fl_fedavg
Suggest making the fact that this is PyTorch-only more explicit, e.g. `fl-pytorch-fedavg`.

2022-01-27 00:08 UTC, jialei777 commented on shrike/pipeline/components/fedavg/spec.yaml
> +  model_input_dir_1:
There should be better ways to handle this. Maybe put all the torch model files in just one folder?

2022-01-27 00:09 UTC, jialei777 commented on shrike/pipeline/components/fedavg/run.py
> +    for i in range(1, 11):
Maybe parse `num_models` first, then those models.

2022-01-27 00:42 UTC, fuhuifang commented on shrike/pipeline/components/fedavg/spec.yaml
> +  model_input_dir_1:
Visually it's better to have 1:1 mapping between input data and component argument ([example](https://ml.azure.com/experiments/id/016ca69b-7d56-47f3-977d-2cd0f4bf852d/runs/178838ba-90b4-4ec4-abec-4ffbb953cc20?wsid=/subscriptions/48bbc269-ce89-4f6f-9a12-c6f91fcb772d/resourcegroups/aml1p-rg/workspaces/aml1p-ml-wus2&tid=72f988bf-86f1-41af-91ab-2d7cd011db47#)). Also for eyes-on testing where user disables data transfer, there's no way to save all models on different datastores into one folder.

2022-01-27 00:46 UTC, fuhuifang commented on shrike/pipeline/components/fedavg/run.py
> +    for i in range(1, 11):
This is the placeholder for defining how an argument should be parsed, to match what we specify in spec.yaml. We need `--model_input_dir_10` even if the actual value of `num_models` is 2.

2022-01-27 00:58 UTC, jialei777 commented on shrike/pipeline/components/fedavg/spec.yaml
> +  model_input_dir_1:
That makes sense.

2022-01-27 00:59 UTC, jialei777 approved these changes

2022-01-27 17:04 UTC, dkmiller approved these changes

2022-01-27 21:13 UTC, merged