Support error threshold in the compute yaml file
Azure/shrike pull request #70
Opened 2021-06-02 18:28 UTC by haozhestat

2021-06-02 18:31 UTC, dkmiller requested changes

2021-06-02 18:31 UTC, dkmiller commented on shrike/pipeline/pipeline_helper.py
> +            error_threshold=error_threshold
Can you add unit tests to verify that this works?

2021-06-02 22:53 UTC, haozhestat commented on shrike/pipeline/pipeline_config.py
> +    parallel_process_count_per_node: Optional[int] = MISSING
@evgri243 : I changed the default value of "parallel_process_count_per_node" from 1 to Null in this line.

2021-06-08 00:28 UTC, haozhestat commented on shrike/pipeline/pipeline_helper.py
> +            error_threshold=error_threshold
@dkmiller and @fuhuifang : I have added a unit test for `_apply_parallel_runsettings()` in the `tests\tests_pipeline\test_pipeline_helper.py` file. Could you take a look?

If this type of unit test looks good to you, I will create another PR to create unit test for all other functions in the `pipeline_helper.py`

2021-06-08 14:46 UTC, dkmiller approved these changes

2021-06-08 17:27 UTC, fuhuifang commented on tests/tests_pipeline/data/test_configuration.yaml
> +  local_steps_folder: ../../steps
Does this relative path work?

2021-06-08 17:27 UTC, fuhuifang commented on tests/tests_pipeline/test_pipeline_helper.py
> +    module_instance_fun = Component._from_module_spec(
Can we use `pipeline_helper.component_load()` directly?

2021-06-08 18:07 UTC, haozhestat commented on tests/tests_pipeline/data/test_configuration.yaml
> +  local_steps_folder: ../../steps
Good catch. Addressed.

2021-06-08 18:08 UTC, haozhestat commented on tests/tests_pipeline/test_pipeline_helper.py
> +    module_instance_fun = Component._from_module_spec(
Yes. I just updated it to `pipeline_helper.component_load()`, which is much simpler than and equivalent with `Component._from_module_spec()`

2021-06-08 21:57 UTC, merged