remove module_name from apply_recommended_runsettings
Azure/shrike pull request #74
Opened 2021-06-03 21:01 UTC by fuhuifang

Urgency: _low_

Currently, users need to call `self.apply_recommended_runsettings(stats_step, "stats_passthrough")`, but the second keyword "stats_passthrough" seems redundant. In this pr, we remove this required field.

2021-06-03 21:28 UTC, dkmiller requested changes

2021-06-03 21:28 UTC, dkmiller commented on shrike/pipeline/pipeline_helper.py
> -        module_name,
Sadly it's not that simple. This would be a breaking change (remove existing parameter) which would break all existing usage of this library.

I see a couple possible options, since Python doesn't support method overloading.

1. Add a _new_ method, with the new set of parameters.
2. Just add a default value of `None` to this parameter, and fall back to `_get_module_name` if it is none.

2021-06-03 21:28 UTC, dkmiller commented on shrike/pipeline/pipeline_helper.py
> +    def _get_module_name_from_module_instance(self, module_instance):
Let's name this `_get_component_name_from_instance` and the param `component_instance`.

2021-06-03 21:38 UTC, fuhuifang commented on shrike/pipeline/pipeline_helper.py
> -        module_name,
I think 2 is better. However, we have to switch the order of `module_name` and `module_instance`, unless we add a default value to `module_instance` as well. I can raise an exception if it is none. Does it work?

2021-06-03 23:21 UTC, dkmiller commented on shrike/pipeline/pipeline_helper.py
> -        module_name,
Yes, I think adding the default of `None` to `module_instance` might make sense. But then the whole method would "smell" a bit strange (`None` as default for two parameters, you'd have to call it like `self.apply_recommended_runsettings(module_instance=foo)`.

Better &mdash; what about `self.apply_smart_runsettings` for the new method? It goes with the "smart" theme of the library, and then we could fix parameter names as well, e.g. `apply_smart_runsettings(component_instance, ...)`.

2021-06-04 00:18 UTC, fuhuifang commented on shrike/pipeline/pipeline_helper.py
> -        module_name,
In my latest commit, the new method `apply_smart_runsettings` is still calling `apply_recommended_runsettings`. Let me know if you think it's better to copy over the underlying code inside `apply_recommended_runsettings`. Otherwise, we can wait until we deprecate `apply_recommended_runsettings`.

2021-06-04 15:04 UTC, dkmiller commented on shrike/pipeline/pipeline_helper.py
> -        module_name,
You did the right thing &mdash; we won't be deprecating methods now that we're "GA", so making the new method point to the old is the way to go.

2021-06-04 16:00 UTC, haozhestat commented
@fuhuifang, could you test the PR by submitting some real AML pipelines using custom_runtime_arguments? I want to make sure that the custom_runtime_arguments can propagate through apply_smart_runsettings().

All others look good to me.

2021-06-04 20:06 UTC, dkmiller requested changes

2021-06-04 20:42 UTC, jfomhover commented
One reason why this argument was given was to enable using the same module under 2 different keys. An example is in a pipeline where a module A is used in 2 locations, once as registered, once as local.

2021-06-04 21:29 UTC, fuhuifang commented
> One reason why this argument was given was to enable using the same module under 2 different keys. An example is in a pipeline where a module A is used in 2 locations, once as registered, once as local.

In this case, I think we could just add this new method for simpler situations, without deprecating the old method.

2021-06-08 22:51 UTC, haozhestat commented on shrike/__init__.py
> +__version__ = "1.1.0"
@fuhuifang: We consider "1.1.0" as our next stable version of "shrike". Could you explain more on your thoughts here?

2021-06-08 22:52 UTC, fuhuifang commented on shrike/__init__.py
> +__version__ = "1.1.0"
@dkmiller mentioned in a previous comment that this will be a breaking API change, so the version should be 1.1.0 instead of 1.0.2

2021-06-08 22:55 UTC, dkmiller commented on shrike/__init__.py
> +__version__ = "1.1.0"
@haozhestat , my take is that we should use semantic versioning.

(major).(minor).(patch)

- breaking change &mapsto; major bump
- net-new functionality &mapsto; minor bump
- bugfix (identical API) &mapsto; patch bump

2021-06-08 22:57 UTC, haozhestat commented on shrike/__init__.py
> +__version__ = "1.1.0"
Got. Thanks.

2021-06-08 22:59 UTC, haozhestat approved these changes

2021-06-09 15:36 UTC, dkmiller approved these changes

2021-06-09 16:31 UTC, merged