Enable Metrics and Item Logging
Azure/shrike pull request #86
Opened 2021-06-12 15:14 UTC by felixnext

Integrate automatic item parsing and started implementation of AML Metrics into the logging class.
Also added some helper functions to automatically output system stats.

## Changes

- Logger class now has item property to log meta information about Dataframe, lists, etc.

## Future

- This is a draft, please do a first review, will implement the remaining metric functions and unit tests shortly

## Key files

- logging.py

## To-do

- [ ] Integrate remaining metric functions
- [ ] Add Unit tests

2021-06-12 18:48 UTC, danrsc commented
Hey @felixnext! Thanks for setting up this feature. I took a look at the draft, and I wasn't able to write comments on it inline, but here are my thoughts:

data_conversions.py
	lines 89, 102, 114, 195, 208, 220, 284, 296, 420, 444, 456, 468:
            in my opinion, all of these cases should raise an error (NotImplementedError or RuntimeError) 
            rather than returning a value. Returning values in these cases to me just makes debugging more
            difficult than raising an error. For functions like is_spark_dataframe returning False makes sense,
            but for other cases I think an error should be raised

logging.py
	line 125: check whether obj is typing.Iterable rather than list. Since str is an iterable have a special case for str
        line 128: make max number of items to print a parameter on the logger that can be controlled. 

        line 192: 
            If we want to have a high level function that tries to infer which aml logging method to use, that's ok,
            but I also want to expose wrappers around all of the AML metric logging functions that can be called directly
            and just add the category keyword and check that DataCategory is public before calling the underlying function.
            I would also like to see those functions exposed without the logger, i.e. I should be able to import them directly
            and call them.

        line 426:
            Why is it necessary to force the caller to call enable_azure_context()? When the caller uses one of the log metric
            functions we can just set the azure context if it is not set. Making the caller do all of this setup feels a bit
            clunky. It is necessary for confidential logging to work, but not for this to work.

2021-06-12 18:50 UTC, danrsc commented
Hey @felixnext! Thanks for integrating this feature into shrike. I took a
look at the draft PR and could not comment directly on it, but here are my
thoughts:

data_conversions.py
lines 89, 102, 114, 195, 208, 220, 284, 296, 420, 444, 456, 468:
            in my opinion, all of these cases should raise an error
(NotImplementedError or RuntimeError)
            rather than returning a value. Returning values in these cases
to me just makes debugging more
            difficult than raising an error. For functions like
is_spark_dataframe returning False makes sense,
            but for other cases I think an error should be raised

logging.py
line 125: check whether obj is typing.Iterable rather than list. Since str
is an iterable have a special case for str
        line 128: make max number of items to print a parameter on the
logger that can be controlled.

        line 192:
            If we want to have a high level function that tries to infer
which aml logging method to use, that's ok,
            but I also want to expose wrappers around all of the AML metric
logging functions that can be called directly
            and just add the category keyword and check that DataCategory
is public before calling the underlying function.
            I would also like to see those functions exposed without the
logger, i.e. I should be able to import them directly
            and call them.

        line 426:
            Why is it necessary to force the caller to call
enable_azure_context()? When the caller uses one of the log metric
            functions we can just set the azure context if it is not set.
Making the caller do all of this setup feels a bit
            clunky. It is necessary for confidential logging to work, but
not for this to work.


On Sat, Jun 12, 2021 at 11:14 AM Felix Geilert ***@***.***>
wrote:

> Integrate automatic item parsing and started implementation of AML Metrics
> into the logging class.
> Also added some helper functions to automatically output system stats.
> Changes
>
>    - Logger class now has item property to log meta information about
>    Dataframe, lists, etc.
>
> Future
>
>    - This is a draft, please do a first review, will implement the
>    remaining metric functions and unit tests shortly
>
> Key files
>
>    - logging.py
>
> To-do
>
>    - Integrate remaining metric functions
>    - Add Unit tests
>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/Azure/shrike/pull/86
> Commit Summary
>
>    - Feat: Added basic structure for data conversions and system
>    information
>    - Feat: Implemented import-safe data conversions
>    - Chore: Added structure in logger and outlined remaining todos for PR
>    - Feat: Added item parsing
>    - Feat: Implemented basic metric components (scalar, list, tabular and
>    image metrics) / improved category handling
>
> File Changes
>
>    - *M* shrike/compliant_logging/__init__.py
>    <https://github.com/Azure/shrike/pull/86/files#diff-072d81acc0e3c639eedb91fa9d9e8a3c214a76fbbb0ab6592d7c6764ab4b0dd3>
>    (2)
>    - *A* shrike/compliant_logging/data_conversions.py
>    <https://github.com/Azure/shrike/pull/86/files#diff-f07a39edb6cd8a4f8d38f2608ae445cbe58027ca215a7e8440c6af517d070fb3>
>    (468)
>    - *M* shrike/compliant_logging/logging.py
>    <https://github.com/Azure/shrike/pull/86/files#diff-65008188a26e9abc25d9276a259d8a6a6863f8f2d88bbb8cdef1f6a692887cc5>
>    (275)
>    - *A* shrike/compliant_logging/logging_helper.py
>    <https://github.com/Azure/shrike/pull/86/files#diff-891635c856cffdb1a67bdbe5965403bdb91b526519573da0bf62bc432dff0a13>
>    (46)
>
> Patch Links:
>
>    - https://github.com/Azure/shrike/pull/86.patch
>    - https://github.com/Azure/shrike/pull/86.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Azure/shrike/pull/86>, or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACYJZOPIIGRDZYHJFRH46ODTSN2WDANCNFSM46S2MACQ>
> .
>

2021-06-15 00:28 UTC, haozhestat commented on shrike/compliant_logging/logging.py
> +        run.log_image(name=name, path=path, plot=plot, description=description)
Sometimes the image file could be very large. If the network bandwidth is limited, it may take longer-than-expected time to upload. We may consider use `run.flush(timeout_seconds=300)` to wait for task queue to be processed.

https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.run.run?view=azure-ml-py#flush-timeout-seconds-300-

2021-06-15 06:33 UTC, felixnext commented on shrike/compliant_logging/data_conversions.py
> +# Copyright (c) Microsoft Corporation.
sure. I split it to avoid files getting too long and make it easier to edit. But we can just as well merge them.

2021-06-15 06:34 UTC, felixnext commented on shrike/compliant_logging/logging.py
> +        run.log_image(name=name, path=path, plot=plot, description=description)
Thats a good point, was not aware of that limitation, thanks :)

2021-06-15 08:27 UTC, felixnext commented on shrike/compliant_logging/logging_helper.py
> +        libs = ["pandas", "numpy", "pyspark"]
I collapesed the library_checks and libs to one argument, so that users can have complete freedom. If they constantly check the same libs they should feel free to write a wrapper function around that

2021-06-15 15:10 UTC, dkmiller commented on shrike/compliant_logging/logging_helper.py
> +# Copyright (c) Microsoft Corporation.
Nit: `helper` is a naming antipattern (just like `utils`). The point of this namespace is that it provides "probe the system" functionality. Not sure I know a better name, but suggest brainstorming one with Haozhe :) .

2021-06-15 15:10 UTC, dkmiller commented on shrike/compliant_logging/logging.py
> +                "Unable to log image metric {} as private, skipping.".format(name)
Nit: use f-strings instead of `.format()` throughout.

2021-06-15 15:10 UTC, dkmiller commented on shrike/compliant_logging/logging.py
> +        if is_vaex_dataframe(value):
Shouldn't this be a set of `if` / `elif` / `elif` / ...?

2021-06-15 15:10 UTC, dkmiller commented on shrike/compliant_logging/logging.py
> +_AMLRun = None
Nit: suggest `_AML_RUN`

2021-06-15 15:10 UTC, dkmiller commented on shrike/compliant_logging/data_conversions.py
> +        raise RuntimeError("Pandas DataFrame not supported in the current environment.")
Suggest to raise the `Public` variant of these exceptions, so that exception message won't be scrubbed by default.

2021-06-15 21:28 UTC, fuhuifang commented on shrike/compliant_logging/logging.py
> +            return "{} | {}".format(type(obj), str(obj))
Just to be consistent with other code in this library, could you use f-string formatting?

2021-06-16 09:56 UTC, felixnext commented on shrike/compliant_logging/logging.py
> +                "Unable to log image metric {} as private, skipping.".format(name)
Hm. I think f-strings were introduced only in 3.6. Since some of the HDI clusters still run 3.5, I used format. Since the rest of the lib uses f-strings anyway, I will change it here. (Also 3.5 is EoL)

2021-06-16 09:58 UTC, felixnext commented on shrike/compliant_logging/logging.py
> +_AMLRun = None
Done

2021-06-16 10:23 UTC, felixnext commented
Okay, adjusted most of the comments above. Will implemented the rest of the code by EoW.

2021-06-16 10:24 UTC, felixnext commented on shrike/compliant_logging/logging.py
> +            if isinstance(obj, Exception):
@dkmiller @haozhestat can you double check this logic for providing infos to exceptions? Would like to make sure that it is conform with compliant guidelines and I did not miss anything!

2021-06-16 15:48 UTC, dkmiller commented on shrike/compliant_logging/logging.py
> +                "Unable to log image metric {} as private, skipping.".format(name)
We made an explicit decision (with Dan Schwartz's buy-in) very early on to support Python &ge; 3.6. So f-strings are fine throughout.

2021-06-19 09:48 UTC, felixnext commented
@haozhestat @danrsc The remaining metric functions should now be implemented. Each log function in the `Run` class should now have an equivalent in the `CompliantLogger` class. All of these functions should work in a similar manner as the `Run` variants, but are also able to take in DataFrames to compute the value manually.
That being said, the documentation [on the Run Class](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.run(class)?view=azure-ml-py#methods) is a bit sparse on how the values should be computed. Therefore it might make sense if someone double checks the computation routines.

@haozhestat As for the Unit-tests, I haven't started those yet. But I would be more than happy if someone from the aml-ds team could pick those up (I am not sure how we want to test the try-except import statements, as they are dependent on the environment or how to test the `Run` class dependent logic as this is dependent on running in an Azure Environment...)

**Bonus**:
A feature suggestion that is not yet implemented but might be helpful for the future: Add an option in the logger to additionally log to the Parent of the `Run` context retrieved -> Makes Metrics available on the experiment level.

2021-06-20 06:00 UTC, haozhestat commented
Hi @felixnext :

> @haozhestat @danrsc The remaining metric functions should now be implemented. Each log function in the `Run` class should now have an equivalent in the `CompliantLogger` class. All of these functions should work in a similar manner as the `Run` variants, but are also able to take in DataFrames to compute the value manually.

Thank you so much for making aml metric logging supported in shrike. I greatly appreciate your contribution.

> That being said, the documentation [on the Run Class](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.run(class)?view=azure-ml-py#methods) is a bit sparse on how the values should be computed. Therefore it might make sense if someone double checks the computation routines.

I totally agree. After this PR is merged and the aml metrics logging feature is released and tested, we will update our documentation to include an introduction on how to use the shrike library to do aml metrics logging. I have created Issue #100 for tracking. (@thomasp-ms F.Y.I.)


> @haozhestat As for the Unit-tests, I haven't started those yet. But I would be more than happy if someone from the aml-ds team could pick those up (I am not sure how we want to test the try-except import statements, as they are dependent on the environment or how to test the `Run` class dependent logic as this is dependent on running in an Azure Environment...)

No problem. I can work on the unit tests for aml metrics logging. (I am currently taking vacations on 6/21-6/25. I will start working on unit tests right after I come back to office on Monday 6/28.)
- For the Azure environment, we have already set up a [service connection](https://github.com/Azure/shrike/blob/308c2566753470239136c54406969f4762fa2537/.github/workflows/python.yml#L155) in our github repo. While doing the unit tests, it can automatically connect to our azureml workspace [github-ci-ml-wus2](https://ml.azure.com/?tid=72f988bf-86f1-41af-91ab-2d7cd011db47&wsid=%2Fsubscriptions%2F48bbc269-ce89-4f6f-9a12-c6f91fcb772d%2Fresourcegroups%2Fgithub-ci-rg%2Fworkspaces%2Fgithub-ci-ml-wus2). 
- For the try-except import statements, I don't have an idea now. I will continue thinking about it after I come back from vacation.

> A feature suggestion that is not yet implemented but might be helpful for the future: Add an option in the logger to additionally log to the Parent of the `Run` context retrieved -> Makes Metrics available on the experiment level.

@dkmiller : Do you know whether the experiment-level metrics logging is available in AML now? I am note quite sure.

2021-06-20 07:08 UTC, felixnext commented
@haozhestat Perfect, thanks! Then I would now hand-off the PR to you (let me know if you need anything more from my side) :)

One of the things I would like to follow up on (but probably with a later PR, as it is end of FY I am sadly a bit short on time) is to refactor to push the wrappers of AML outside the metrics class (to have a clearer separation of the logic) and then just have the logger class call them.

Anyway, I look forward to the version release that contains the changes :) Also enjoy your vacation!!

2021-06-28 15:41 UTC, haozhestat commented
> @haozhestat Perfect, thanks! Then I would now hand-off the PR to you (let me know if you need anything more from my side) :)
> 
> One of the things I would like to follow up on (but probably with a later PR, as it is end of FY I am sadly a bit short on time) is to refactor to push the wrappers of AML outside the metrics class (to have a clearer separation of the logic) and then just have the logger class call them.
> 
> Anyway, I look forward to the version release that contains the changes :) Also enjoy your vacation!!

@felixnext : I just returned from the vacation. I will pick up your work and write unit tests this week. My target is to complete all unit tests by EOW.

2021-07-06 03:29 UTC, haozhestat commented
> @haozhestat Perfect, thanks! Then I would now hand-off the PR to you (let me know if you need anything more from my side) :)
> 
> One of the things I would like to follow up on (but probably with a later PR, as it is end of FY I am sadly a bit short on time) is to refactor to push the wrappers of AML outside the metrics class (to have a clearer separation of the logic) and then just have the logger class call them.
> 
> Anyway, I look forward to the version release that contains the changes :) Also enjoy your vacation!!

Hi @felixnext : I have completed Part I of the unit tests for the aml metric logging feature that you are brining into shrike.compliant_logging. Below is my pull request. Could you (and @dkmiller) take a look and leave some comments?

 https://github.com/Azure/shrike/pull/117

Next step: I aim to complete Part I of the unit tests by the end of this week.

2021-07-08 14:25 UTC, felixnext commented on shrike/compliant_logging/logging.py
> +                    else:
This part can cause problems! (as value is not a dict). Remove the if-else loop here (not needed)

2021-07-08 17:11 UTC, dkmiller requested changes

2021-07-08 17:11 UTC, dkmiller commented on setup.py
> +    install_requires=["azureml-core==1.31.0"],
Why is this here and not in the requirements files?

2021-07-08 17:11 UTC, dkmiller commented on shrike/compliant_logging/system_info.py
> +        logger = logging.getLogger()
Nit: should be `logging.getLogger(__name__)`.

2021-07-08 17:11 UTC, dkmiller commented on shrike/compliant_logging/system_info.py
> +    logger.info("| CPU     = {}".format(uname.processor), category=DataCategory.PUBLIC)
Nit: f-strings here.

2021-07-08 21:25 UTC, haozhestat commented on setup.py
> +    install_requires=["azureml-core==1.31.0"],
Sure. I have moved "azureml-core==1.31.0" into a new requirement file called "requirements-logging.txt".

2021-07-08 21:25 UTC, haozhestat commented on shrike/compliant_logging/system_info.py
> +        logger = logging.getLogger()
Addressed.

2021-07-08 21:25 UTC, haozhestat commented on shrike/compliant_logging/system_info.py
> +    logger.info("| CPU     = {}".format(uname.processor), category=DataCategory.PUBLIC)
Addressed.

2021-07-08 21:38 UTC, haozhestat commented on shrike/compliant_logging/logging.py
> +                    else:
@felixnext : I am a bit confused about your comment. These lines are under the if condition: `if isinstance(value, dict):`, so value must be a dict here.

![image](https://user-images.githubusercontent.com/18077361/124994025-0d20bf00-dffa-11eb-8d06-5a481e0e1aab.png)

2021-07-08 22:00 UTC, dkmiller approved these changes

2021-07-09 06:30 UTC, felixnext commented on shrike/compliant_logging/logging.py
> +                    else:
Oh, you are right. My bad. I ran into this problem in one of my modules but I partly rewrote the function here. So you are right, the problem should not occur.
However, the if-else loop should not be needed here and might be removed to simplify the code

2021-07-09 19:01 UTC, haozhestat commented on shrike/compliant_logging/logging.py
> +                    else:
Got it. I have just removed the if-else loop, as you suggested.

2021-07-09 21:13 UTC, haozhestat commented
@dkmiller and @felixnext : I just tested the aml metrics logging feature using a real pipeline of accelerator repo. It works well!

Run URL: https://ml.azure.com/runs/d7b53d7d-1f90-49e9-8984-c1742287f15b?wsid=/subscriptions/48bbc269-ce89-4f6f-9a12-c6f91fcb772d/resourcegroups/aml1p-rg/workspaces/aml1p-ml-wus2&tid=72f988bf-86f1-41af-91ab-2d7cd011db47#metrics

![image](https://user-images.githubusercontent.com/18077361/125136512-cc8b7900-e0bf-11eb-9ed2-40aee24e929f.png)

![image](https://user-images.githubusercontent.com/18077361/125136523-d4e3b400-e0bf-11eb-94d1-02b46ac873b2.png)

2021-07-09 22:01 UTC, merged