Implement a method that extracts all Python package dependencies
Azure/shrike pull request #90
Opened 2021-06-14 23:44 UTC by fuhuifang

[ ] Implement the method to extract all dependencies and write to a file under root
[ ] Add unit tests
[ ] Check if CG is run

2021-06-15 21:31 UTC, fuhuifang commented
This code assumes `conda_dependencies`, `conda_dependencies_file`, `pip_requirements_file` can co-exist in yaml. Please let me know if this is not the case.

2021-06-15 22:27 UTC, haozhestat requested changes

2021-06-16 15:37 UTC, dkmiller requested changes

2021-06-16 15:37 UTC, dkmiller commented on shrike/build/commands/prepare.py
> +                        if pip_dependencies_item.startswith("--index-url"):
You can actually keep this (it's ok if the generated requirements.txt file includes `--index-url` lines).

Those won't do anything "funny" with component governance.

2021-06-16 15:37 UTC, dkmiller commented on shrike/build/commands/prepare.py
> +    def _extract_python_package_dependencies(self, requirements):
Is this extracting from requirements.txt or Conda files? The parameter name suggests former, but implementation suggests the latter.

2021-06-16 15:37 UTC, dkmiller commented on shrike/build/commands/prepare.py
> +                            x.replace("\n", "") for x in pip_dependencies
Are you sure this is needed? I think newlines in the generated requirements.txt file are ok.

2021-06-16 15:37 UTC, dkmiller commented on shrike/build/commands/prepare.py
> +            with open(component, "r") as spec_file:
Suggestion: have a "try / except" around all these `open` statements where you catch the `filenotfounderror` and register an error.

That way, wrong path to environment.yml doesn't catastrophically break the build.

2021-06-16 18:40 UTC, dkmiller commented on tests/tests_build/commands/test_prepare.py
> +    prep.attach_workspace(TESTING_WORKSPACE)
A bit curious, why is workspace attach needed here? Ditto with some of the other tests?

2021-06-16 18:48 UTC, fuhuifang commented on tests/tests_build/commands/test_prepare.py
> +    prep.attach_workspace(TESTING_WORKSPACE)
Thanks for catching this. Just removed all necessary calls.

2021-06-16 18:49 UTC, dkmiller approved these changes

2021-06-16 19:07 UTC, haozhestat approved these changes
After this version is released, please upload the wheel file to the Polymer feed. Thanks, @fuhuifang.

2021-06-16 20:30 UTC, merged

2021-06-18 17:09 UTC, haozhestat commented on shrike/__init__.py
> +__version__ = "1.3.2"
@fuhuifang : I just realized that we skipped the "1.2.0", "1.3.0" and "1.3.1" versions of shrike. The current latest version of shrike is "1.3.2". No actions are required now. Let's follow the versioning convention in the future.

![image](https://user-images.githubusercontent.com/18077361/122595200-f4d20b80-d01c-11eb-9bab-b8bfa2056728.png)

2021-06-18 17:48 UTC, fuhuifang commented on shrike/__init__.py
> +__version__ = "1.3.2"
Thanks Haozhe for the reminder! I didn't realize this at all. Will pay attention next time 😄

2021-06-18 17:50 UTC, haozhestat commented on shrike/__init__.py
> +__version__ = "1.3.2"
@fuhuifang : No problem at all. My bad. I should have caught it when I reviewed the PR.