RFC draft for image override
Azure/shrike pull request #93
Opened 2021-06-17 16:08 UTC by fuhuifang

2021-06-17 18:15 UTC, haozhestat commented on shrike/pipeline/rfc-image-override.md
> +
At the submission time, the library may need to check whether it is using the remote component or local component. As the component spec YAML will be modified, only local could be used after image overrides.

2021-06-17 20:46 UTC, dkmiller requested changes

2021-06-17 20:46 UTC, dkmiller commented on shrike/pipeline/rfc-image-override.md
> +To allow components to operate across multiple workspaces (eyes-off vs. eyes-on), the image and base url of Python Package Index need to be adjusted accordingly. For example, given a signed component
Removing `--index-url` shouldn't be necessary. Even MyData workspaces have a connection to that feed.

For "public" workspaces, it's easy (\& documented) how to create the connection.

2021-06-17 20:46 UTC, dkmiller commented on shrike/pipeline/rfc-image-override.md
> +The `shrike.pipeline` library should **automatically detect the tenant id** and decide if image override is required. If required, it will **modify all `component_spec.yaml` using the mapping defined
Hopefully, we shouldn't have to modify Conda dependencies.

The spec modification + revert should happen in try / catch, so that even if our code fails, the changes are reverted.

2021-06-17 20:46 UTC, dkmiller commented on shrike/pipeline/rfc-image-override.md
> +      environment.docker.image:
I like this! Just to be explicit, it's a JSONPath.

2021-06-17 20:46 UTC, dkmiller commented on shrike/pipeline/rfc-image-override.md
> +        polymerprod.azurecr.io/polymercd/prod_official/azureml_base_gpu_openmpi312cuda101cudnn7: mcr.microsoft.com/azureml/openmpi3.1.2-cuda10.1-cudnn7-ubuntu18.04
Suggest we allow both "naive" string substitution \& regex-based substitution.

i.e.,

```yaml
'polymerprod.azurecr.io/polymercd/prod_official/(.+)': 'polymerdev.azurecr.io/polymercd/prod_official/$1'
```

Use something like [re.sub](https://stackoverflow.com/a/14007559).

2021-06-17 20:46 UTC, dkmiller commented on shrike/pipeline/rfc-image-override.md
> +- We would then have to support editing all other fields (tags, etc.)
If implementation is done properly, this should come "for free".

2021-06-17 20:46 UTC, dkmiller commented on shrike/pipeline/rfc-image-override.md
> +- MCR and Polymer have different image names, both of which may change over time. There's no clear 1:1 mapping.
Fortunately, `polymerdev` is in MSIT and you can already get that attached to MyData. Also, clear 1:1 mapping between that and &ast;prod.

2021-06-18 11:23 UTC, danrsc commented on shrike/pipeline/rfc-image-override.md
> +    72f988bf-86f1-41af-91ab-2d7cd011db47:
I suggest allowing a tenant alias so this becomes readable. Perhaps the file name used to define a tenant (e.g. if eyes_off.yaml defines the tenant id 72f...) "eyes_off" could be used here

2021-06-18 11:26 UTC, danrsc commented on shrike/pipeline/rfc-image-override.md
> +        eyesoff: dev
It tags doing something functional here?

2021-06-18 11:30 UTC, danrsc commented on shrike/pipeline/rfc-image-override.md
> +- This would edit the users' YAML files. Potential for concern with registered components.
We don't have to literally edit the user's files. We could create a copy at submission time (for unpublished) or publication time to publish, then delete the copy

2021-06-18 11:31 UTC, danrsc commented on shrike/pipeline/rfc-image-override.md
> +
I don't understand the publication story. Will we run through the workspaces and create the appropriate overrides for each workspace at publication time?

2021-06-18 18:06 UTC, fuhuifang commented on shrike/pipeline/rfc-image-override.md
> +        eyesoff: dev
Not really. It's just the "tags" displayed on the portal.

2021-06-18 18:09 UTC, fuhuifang commented on shrike/pipeline/rfc-image-override.md
> +
No, we do not publish the overrides for now. Publishing components will need to go through "build" part of this library, instead of "pipeline".

2021-06-23 19:58 UTC, fuhuifang commented on shrike/pipeline/rfc-image-override.md
> +  - Solution 2: create a copy of spec and the delete
Personally, I'd prefer solution 2. Potential risk: using the wrong version of spec for submission.

2021-06-23 20:10 UTC, dkmiller approved these changes

2021-06-23 21:24 UTC, merged