add sweep component support to shrike.pipeline
Azure/shrike pull request #99
Opened 2021-06-18 22:25 UTC by ShizeSu06

In this PR, I added sweep component support to shrike.pipeline package.

## To-do

- [ ] add sweep component examples to accelerator repo.

2021-06-18 22:35 UTC, fuhuifang requested changes

2021-06-18 22:35 UTC, fuhuifang commented on shrike/pipeline/pipeline_helper.py
> +    def _apply_sweep_runsettings(
@ShizeSu06 Could you integrate this new method and `apply_recommended_runsettings()`? Also could you add some unit tests?

2021-06-18 22:41 UTC, haozhestat requested changes

2021-06-18 22:41 UTC, haozhestat commented on shrike/__init__.py
> +__version__ = "1.3.3"
Could you bump the second digit (1.3.2 --> 1.4.0)? I think adding sweep component is an important change.

2021-06-18 22:41 UTC, haozhestat commented on shrike/pipeline/pipeline_helper.py
> +    def _apply_sweep_runsettings(
Could you add a unit test for `_apply_sweep_runsettings()` function?

2021-06-18 22:41 UTC, haozhestat commented on shrike/pipeline/pipeline_helper.py
> +            target if target is not None else self.config.compute.linux_cpu_prod_target
Does sweep component only run in the linux VM? Could you confirm whether windows OS and detonation chamber are supported for sweep component?

If there are some restrictions on compute target, could you some code to raise ValueError? You could find the example here: https://github.com/Azure/shrike/blob/308c2566753470239136c54406969f4762fa2537/shrike/pipeline/pipeline_helper.py#L451

2021-06-18 22:41 UTC, haozhestat commented on shrike/pipeline/pipeline_helper.py
> +            module_instance.runsettings.sweep.early_termination.configure(
You could combine these configuration together. Here is an example: https://github.com/Azure/shrike/blob/308c2566753470239136c54406969f4762fa2537/shrike/pipeline/pipeline_helper.py#L488

2021-06-18 22:41 UTC, haozhestat commented on shrike/pipeline/pipeline_helper.py
> +
[apply_smart_runsettings()](https://github.com/Azure/shrike/blob/308c2566753470239136c54406969f4762fa2537/shrike/pipeline/pipeline_helper.py#L733) is the entry function for run setting configuration. Could you add `_apply_sweep_runsettings` into `apply_smart_runsettings()` and setup the auto detection of sweep component?

2021-06-18 22:44 UTC, haozhestat commented
@ShizeSu06 :  Before you merge this PR, could you please use shrike to submit a pipeline which contains at least 1 sweep component to an AML workspace? It will help us check whether all the configurations work well and whether the results could be properly generated.

2021-06-18 23:45 UTC, ShizeSu06 commented on shrike/pipeline/pipeline_helper.py
> +            module_instance.runsettings.sweep.early_termination.configure(
@haozhestat For sweep, these parameters are shared in both sweep component definition yaml file as well as the runsettings config here. If we combine them together, we might have a concern (which need to be verified later) that it might override some setting in yaml file to "None" when user only specify a subset of these runseting parameters, which is undesired/incorrect behavior. So based on offline conversation with Haozhe and Fuhui, we would keep it as it is for now, and if later we found that concern is not an issue then we could revise the code by combining similar items together to be more elegant.

2021-06-18 23:46 UTC, ShizeSu06 commented
> @ShizeSu06 : Before you merge this PR, could you please use shrike to submit a pipeline which contains at least 1 sweep component to an AML workspace? It will help us check whether all the configurations work well and whether the results could be properly generated.

Sure! I will do such a e2e testing before merging the PR.

2021-06-18 23:46 UTC, haozhestat commented on shrike/pipeline/pipeline_helper.py
> +        if sweep:
Could you please move this block up so that it runs before the following code?

```
        if windows:
            # no detonation chamber, we an't use "use_local" here
            self._apply_windows_runsettings(
                module_name, module_instance, mpi=mpi, **custom_runtime_arguments
            )
            return
```

2021-06-18 23:47 UTC, haozhestat commented on shrike/pipeline/pipeline_helper.py
> +        if sweep:
Otherwise, it will enter "_apply_windows_settings()" first if the computer is windows.

2021-06-18 23:57 UTC, ShizeSu06 commented on shrike/pipeline/pipeline_helper.py
> +
updated accordingly.

2021-06-19 00:01 UTC, ShizeSu06 commented on shrike/pipeline/pipeline_helper.py
> +        if sweep:
updated.

2021-06-19 00:13 UTC, ShizeSu06 commented on shrike/__init__.py
> +__version__ = "1.3.3"
sure, updated to use 1.4.0

2021-06-19 00:13 UTC, ShizeSu06 commented on shrike/pipeline/pipeline_helper.py
> +    def _apply_sweep_runsettings(
sure, I'd add unit tests to this PR next week.

2021-06-19 00:14 UTC, ShizeSu06 commented on shrike/pipeline/pipeline_helper.py
> +            target if target is not None else self.config.compute.linux_cpu_prod_target
updated accordingly

2021-06-19 00:15 UTC, ShizeSu06 commented on shrike/pipeline/pipeline_helper.py
> +    def _apply_sweep_runsettings(
Added integration with apply_recommended_runsettings(). will also add unit tests next week to this PR.

2021-06-25 22:38 UTC, fuhuifang approved these changes
Sign off as-is. Will let @haozhestat provide feedbacks on unit testing part.

2021-06-28 16:06 UTC, haozhestat commented on shrike/pipeline/pipeline_helper.py
> +    def _apply_sweep_runsettings(
@ShizeSu06 Sounds good to me.

2021-06-28 16:15 UTC, haozhestat commented on shrike/__init__.py
> +__version__ = "1.4.0"
Could you update the version number to "1.5.0" as "1.4.0" has been taken?

2021-06-28 16:18 UTC, ShizeSu06 commented on shrike/__init__.py
> +__version__ = "1.4.0"
sure!

2021-06-30 16:25 UTC, haozhestat commented on tests/tests_pipeline/sample/steps/sweep_component/run.py
> +import argparse
Please add copyright statement here. Otherwise the ci-gate build with fail.

2021-06-30 16:26 UTC, haozhestat commented on tests/tests_pipeline/test_pipeline_helper.py
> +    assert step_instance.runsettings.sweep.timeout_minutes == timeout_minutes
You may need another line break here.

2021-06-30 16:27 UTC, haozhestat approved these changes

2021-06-30 16:57 UTC, ShizeSu06 commented on tests/tests_pipeline/sample/steps/sweep_component/run.py
> +import argparse
actually I saw the failure and already pushed a commit adding the copyright info^_^

2021-06-30 17:02 UTC, ShizeSu06 commented on tests/tests_pipeline/test_pipeline_helper.py
> +    assert step_instance.runsettings.sweep.timeout_minutes == timeout_minutes
I applied the black formatting to fix the issue.

2021-06-30 20:44 UTC, merged